### ISSUE TITLE
Transfer to personal account?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/testrmd#23]
@rmflight :wave: according to our [recently created package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages) this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by rmflight** [comment]
Thanks @maelle !! Transferred. Maybe this will motivate me to look into the various issues that have been filed and see if I can resurrect it.

**Comment by coatless** [comment]
@rmflight note that [`{pointblank}`](https://github.com/rich-iannone/pointblank) has really carried this idea forward.

**Comment by maelle** [comment]
Thank you @rmflight!
